/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTenantsRouteImport } from './routes/_authenticated/app.tenants'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppRentRouteImport } from './routes/_authenticated/app.rent'
import { Route as AuthenticatedAppPropertiesRouteImport } from './routes/_authenticated/app.properties'
import { Route as AuthenticatedAppMyRentRouteImport } from './routes/_authenticated/app.my-rent'
import { Route as AuthenticatedAppMyElectricityRouteImport } from './routes/_authenticated/app.my-electricity'
import { Route as AuthenticatedAppElectricityRouteImport } from './routes/_authenticated/app.electricity'
import { Route as AuthenticatedAppCalculatorRouteImport } from './routes/_authenticated/app.calculator'
import { Route as AuthenticatedAppAiRouteImport } from './routes/_authenticated/app.ai'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTenantsRoute = AuthenticatedAppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRentRoute = AuthenticatedAppRentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPropertiesRoute =
  AuthenticatedAppPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMyRentRoute = AuthenticatedAppMyRentRouteImport.update({
  id: '/my-rent',
  path: '/my-rent',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMyElectricityRoute =
  AuthenticatedAppMyElectricityRouteImport.update({
    id: '/my-electricity',
    path: '/my-electricity',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppElectricityRoute =
  AuthenticatedAppElectricityRouteImport.update({
    id: '/electricity',
    path: '/electricity',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCalculatorRoute =
  AuthenticatedAppCalculatorRouteImport.update({
    id: '/calculator',
    path: '/calculator',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAiRoute = AuthenticatedAppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/calculator': typeof AuthenticatedAppCalculatorRoute
  '/app/electricity': typeof AuthenticatedAppElectricityRoute
  '/app/my-electricity': typeof AuthenticatedAppMyElectricityRoute
  '/app/my-rent': typeof AuthenticatedAppMyRentRoute
  '/app/properties': typeof AuthenticatedAppPropertiesRoute
  '/app/rent': typeof AuthenticatedAppRentRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/tenants': typeof AuthenticatedAppTenantsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/calculator': typeof AuthenticatedAppCalculatorRoute
  '/app/electricity': typeof AuthenticatedAppElectricityRoute
  '/app/my-electricity': typeof AuthenticatedAppMyElectricityRoute
  '/app/my-rent': typeof AuthenticatedAppMyRentRoute
  '/app/properties': typeof AuthenticatedAppPropertiesRoute
  '/app/rent': typeof AuthenticatedAppRentRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/tenants': typeof AuthenticatedAppTenantsRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/ai': typeof AuthenticatedAppAiRoute
  '/_authenticated/app/calculator': typeof AuthenticatedAppCalculatorRoute
  '/_authenticated/app/electricity': typeof AuthenticatedAppElectricityRoute
  '/_authenticated/app/my-electricity': typeof AuthenticatedAppMyElectricityRoute
  '/_authenticated/app/my-rent': typeof AuthenticatedAppMyRentRoute
  '/_authenticated/app/properties': typeof AuthenticatedAppPropertiesRoute
  '/_authenticated/app/rent': typeof AuthenticatedAppRentRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/tenants': typeof AuthenticatedAppTenantsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/ai'
    | '/app/calculator'
    | '/app/electricity'
    | '/app/my-electricity'
    | '/app/my-rent'
    | '/app/properties'
    | '/app/rent'
    | '/app/reports'
    | '/app/tenants'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/ai'
    | '/app/calculator'
    | '/app/electricity'
    | '/app/my-electricity'
    | '/app/my-rent'
    | '/app/properties'
    | '/app/rent'
    | '/app/reports'
    | '/app/tenants'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/ai'
    | '/_authenticated/app/calculator'
    | '/_authenticated/app/electricity'
    | '/_authenticated/app/my-electricity'
    | '/_authenticated/app/my-rent'
    | '/_authenticated/app/properties'
    | '/_authenticated/app/rent'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/tenants'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tenants': {
      id: '/_authenticated/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AuthenticatedAppTenantsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rent': {
      id: '/_authenticated/app/rent'
      path: '/rent'
      fullPath: '/app/rent'
      preLoaderRoute: typeof AuthenticatedAppRentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/properties': {
      id: '/_authenticated/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AuthenticatedAppPropertiesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/my-rent': {
      id: '/_authenticated/app/my-rent'
      path: '/my-rent'
      fullPath: '/app/my-rent'
      preLoaderRoute: typeof AuthenticatedAppMyRentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/my-electricity': {
      id: '/_authenticated/app/my-electricity'
      path: '/my-electricity'
      fullPath: '/app/my-electricity'
      preLoaderRoute: typeof AuthenticatedAppMyElectricityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/electricity': {
      id: '/_authenticated/app/electricity'
      path: '/electricity'
      fullPath: '/app/electricity'
      preLoaderRoute: typeof AuthenticatedAppElectricityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/calculator': {
      id: '/_authenticated/app/calculator'
      path: '/calculator'
      fullPath: '/app/calculator'
      preLoaderRoute: typeof AuthenticatedAppCalculatorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai': {
      id: '/_authenticated/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AuthenticatedAppAiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAiRoute: typeof AuthenticatedAppAiRoute
  AuthenticatedAppCalculatorRoute: typeof AuthenticatedAppCalculatorRoute
  AuthenticatedAppElectricityRoute: typeof AuthenticatedAppElectricityRoute
  AuthenticatedAppMyElectricityRoute: typeof AuthenticatedAppMyElectricityRoute
  AuthenticatedAppMyRentRoute: typeof AuthenticatedAppMyRentRoute
  AuthenticatedAppPropertiesRoute: typeof AuthenticatedAppPropertiesRoute
  AuthenticatedAppRentRoute: typeof AuthenticatedAppRentRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppTenantsRoute: typeof AuthenticatedAppTenantsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAiRoute: AuthenticatedAppAiRoute,
  AuthenticatedAppCalculatorRoute: AuthenticatedAppCalculatorRoute,
  AuthenticatedAppElectricityRoute: AuthenticatedAppElectricityRoute,
  AuthenticatedAppMyElectricityRoute: AuthenticatedAppMyElectricityRoute,
  AuthenticatedAppMyRentRoute: AuthenticatedAppMyRentRoute,
  AuthenticatedAppPropertiesRoute: AuthenticatedAppPropertiesRoute,
  AuthenticatedAppRentRoute: AuthenticatedAppRentRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppTenantsRoute: AuthenticatedAppTenantsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
